- hosts: all
  become: true
  vars:
    ansible_user: root
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Add user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Install pip3
      apt:
        name: python3-pip
        state: present

    - name: Install docker-compose
      pip:
        name: docker-compose
        state: present
